project:
  type: book
  output-dir: docs

book:
  title: "Visualization for Social Data Science"
  author: "Roger Beecham and Robin Lovelace"
  description: ""
  # cover-image: images/cover.png
  site-url: https://roger-beecham/vis4gds
  repo-url: https://github.com/rogerbeecham/vis4gds/
  repo-branch: master
  repo-actions: [edit]
  sharing: [twitter]
  chapters:
    - index.qmd
  # - preface.qmd
  #   - part: dice.qmd
  #     chapters:
    - 01-intro.qmd
    - 02-data.qmd
    - 03-visual.qmd
    - 04-explore.qmd
    - 05-network.qmd
    - 06-model.qmd
    - 07-uncertainty.qmd
    - 08-storytelling.qmd
    - references.qmd
  #       - packages.qmd
  #   - part: cards.qmd
  #     chapters:
  #       - objects.qmd
  #       - notation.qmd
  #       - modifying.qmd
  #       - environments.qmd
  #   - part: slots.qmd
  #     chapters:
  #       - programs.qmd
  #       - s3.qmd
  #       - loops.qmd
  #       - speed.qmd
  appendices:
    - a1-data.qmd
    - a2-visual.qmd
  #   - a3-updating.qmd
  #   - a4-data.qmd
  #   - a5-debug.qmd

bibliography: references.bib
suppress-bibliography: true

format:
  html:
    theme: cosmo
    # cover-image: cover.png
    code-link: true
    html-math-method: katex
