name: PRs
on: pull_request

jobs:
  bookdown:
    name: Test-quarto
    runs-on: ubuntu-latest
    container: geocompr/geocompr:geocompy
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Render
        run: |
          quarto render
          ls docs
